name: Java CI

#Immer beim Pushen soll es Ausgef端hrt werden
on:
  push:

#Wir legen die Jobs Fest
jobs:
  # Wir bauen und Testen direkt in einem
  build-and-test:
    runs-on: ubuntu-latest  #VM festlegen f端r Workflow 
    steps:
      - uses: actions/checkout@v3 # Den Code holen 

      - uses: actions/setup-java@v3 # Java Version festlegen
        with:
          java-version: 17

    # Wir erstellen den Bin ordner 
      - run: mkdir -p bin

    # Wir Kompilieren in den Bin Ordner 
      - run: | 
         javac -d bin src/*.java
         echo "Kompiliere Dateien\n"

    # Wir f端hren den Code aus 
      - run: |
         java -cp bin TempConverter
         echo "F端hre Code aus\n"